import { Router, type IRouter } from "express";
import healthRouter from "./health";
import aiRouter from "./ai";
import adminRouter from "./admin";
import adminExtraRouter from "./adminExtra";
import adminCmsRouter from "./adminCms";
import adminCoursesRouter from "./adminCourses";
import adminUsersRouter from "./adminUsers";
import adminNotificationsRouter from "./adminNotifications";
import adminMonetizationRouter from "./adminMonetization";
import adminDiagnosticRouter from "./adminDiagnostic";
import adminContentRouter from "./adminContent";
import contentRouter from "./content";
import sessionsRouter from "./sessions";
import paymentsRouter from "./payments";
import adminTeachersRouter from "./adminTeachers";
import teacherPortalRouter from "./teacherPortal";
import studentTeacherRouter from "./studentTeacher";
import profileRouter from "./profile";
import socialRouter from "./social";
import adminSocialRouter from "./adminSocial";
import feedbackRouter from "./feedbackRoutes";
import studyContentRouter from "./studyContent";
import listeningExercisesRouter from "./listeningExercises";

const router: IRouter = Router();

router.use(healthRouter);
router.use(aiRouter);
router.use(adminRouter);
router.use(adminExtraRouter);
router.use(adminCmsRouter);
router.use(adminCoursesRouter);
router.use(adminUsersRouter);
router.use(adminNotificationsRouter);
router.use(adminMonetizationRouter);
router.use(adminDiagnosticRouter);
router.use(adminContentRouter);
router.use(contentRouter);
router.use(sessionsRouter);
router.use(paymentsRouter);
router.use(adminTeachersRouter);
router.use(teacherPortalRouter);
router.use(studentTeacherRouter);
router.use(profileRouter);
router.use(socialRouter);
router.use(adminSocialRouter);
router.use(feedbackRouter);
router.use(studyContentRouter);
router.use(listeningExercisesRouter);

export default router;
