const colors = {
  light: {
    text: "#111827",
    tint: "#185FA5",
    background: "#F4F6FA",
    foreground: "#111827",
    card: "#FFFFFF",
    cardForeground: "#111827",
    primary: "#185FA5",
    primaryForeground: "#FFFFFF",
    secondary: "#E8F0FB",
    secondaryForeground: "#185FA5",
    muted: "#E5E7EB",
    mutedForeground: "#6B7280",
    accent: "#1D9E75",
    accentForeground: "#FFFFFF",
    destructive: "#D85A30",
    destructiveForeground: "#FFFFFF",
    border: "#E5E7EB",
    input: "#FFFFFF",
    warning: "#BA7517",
    warningForeground: "#FFFFFF",
    success: "#1D9E75",
    successForeground: "#FFFFFF",
    purple: "#6B21A8",
    purpleForeground: "#FFFFFF",
    infoBg: "#E3F2FD",
    warningBg: "#FFF8E1",
    errorBg: "#FBE9E7",
    successBg: "#E8F5E9",
  },
  dark: {
    text: "#F9FAFB",
    tint: "#4B9FE5",
    background: "#141924",
    foreground: "#F9FAFB",
    card: "#1E2535",
    cardForeground: "#F9FAFB",
    primary: "#4B9FE5",
    primaryForeground: "#FFFFFF",
    secondary: "#1E2535",
    secondaryForeground: "#93C5FD",
    muted: "#2D3748",
    mutedForeground: "#9CA3AF",
    accent: "#1D9E75",
    accentForeground: "#FFFFFF",
    destructive: "#D85A30",
    destructiveForeground: "#FFFFFF",
    border: "#2D3748",
    input: "#1E2535",
    warning: "#F59E0B",
    warningForeground: "#FFFFFF",
    success: "#1D9E75",
    successForeground: "#FFFFFF",
    purple: "#A855F7",
    purpleForeground: "#FFFFFF",
    infoBg: "#1E3A5F",
    warningBg: "#3D2B00",
    errorBg: "#3D1A0F",
    successBg: "#0D2B1E",
  },
  radius: 12,
};

export default colors;
